#!/usr/bin/env bash

trap 'exit' ERR

DISTRO=`uname -r | cut -d '-' -f 3`

# Place all required rc_files here
rc_list=(".vimrc" ".bashrc" ".zshrc");

# Check the kernel version and install ZSH accordingly
if [ "$DISTRO" == 'ARCH' ]; then
    sudo pacman -S zsh zsh-completions --noconfirm
else
    sudo apt-get -y install zsh
fi

# Check if which zsh is in /etc/shells
flag=0

for shell in $(cat /etc/shells)
do
    if [ "$shell" == $(which zsh) ]; then
        # Some Acknowledgements :P
        echo 'Congrats!! ZSH found in /etc/shells'; sleep 3
        
        # Change the default shell
        chsh -s $(which zsh)
        flag=1
        break
    fi
done

if [ $flag -eq 0 ]; then
    echo "Sorry, ZSH not found in /etc/shell :("
    exit 1

else
    echo 'Installing RC files...'
    for rc_file in "${rc_list[@]}"; do
        if [[ -f $rc_file || -L $rc_file ]]; then
            echo 'Backing up previous files...'
            mv "$HOME/$rc_file" "$HOME/$rc_file".backup
        fi

        cp "$HOME/dotfiles/$rc_file" "$HOME/$rc_file"
    done

    source "$HOME"/.zshrc
    echo "Setup successful !!"
fi
